### ISSUE TITLE
Add a `--debug` option to display debug messages

### ISSUE THREAD

**Issue by elboulangero** [nicklan/pnmixer#102]
At the moment, the only way to see debug messages is to compile PNMixer with the `--enable-debug` option.

I would prefer to have the debug messages available all the time, and to enable them with a `--debug` option (or `--verbose`). It just seems easier to me (I never bother to compile with `--enable-debug`), and it's also easier with people who send bug reports, because we don't have to ask them to recompile PNMixer to have a verbose output.

I don't even know if it's worth keeping a `--enable-debug` option at compile time after that, because then it's just about compilation options. Maybe there's no need to have two sets of compilation options, I personally always compile with `-Wall -Werror`.

But on the other hand, I'm not a packager. Maybe other people know better than me.

Any thoughts on that ?

**Comment by hasufell** [comment]
Well, regarding `-Werror`, it is highly discouraged to use that as release CFLAGS (there are tons of failures this can cause that won't even break the program). That flag should only be used for development. And indeed, we don't need configure switches to set our CFLAGS.

**Comment by hasufell** [comment]
see https://github.com/nicklan/pnmixer/pull/106
