### ISSUE TITLE
pop menu item ”_Mute“ can not be translated

### ISSUE THREAD

**Issue by LastAvenger** [nicklan/pnmixer#104]
![img](https://img.vim-cn.com/d9/8fd9397dcefe10ded244f850d3ebde429ae441.png)

I am doing the simplified chinese translation for pnmixer,  but I found the pop menu  item "_Mute" cannot be translated.

In all the *.po file has string "Mute" but have no "_Mute",  so add one can fix this bugs.

```po
+ msgid "_Mute"
+ msgstr "_Mute"
```
I am no ensure that it is a correctly way, so I open this issue~

(forgive my poor english)

**Comment by elboulangero** [comment]
Thx :)
