### ISSUE TITLE
New Icon issue

### ISSUE THREAD

**Issue by Makitk** [nicklan/pnmixer#121]
The new icon overwrites the previous one where it showed how loud the setting was by adding/removing soundwaves.
Now I can no longer clearly see in the taskbar what loudness my volume is set to.
Please return to the old icon, tell me how to return to the old icon, or adapt the new icon to show this visual cue.

**Comment by elboulangero** [comment]
Hi, which version of PNMixer are you using ?

I don't really understand the problem. Which icon set do you use ? PNMixer icon, or an icon set from the system ? (you can see that by opening the Preferences -> View -> Icon Theme). Feel free to paste a screenshot also. Thx !

**Comment by Makitk** [comment]
Well, to my knowledge I was still using the Crunchbang icons until I ran an upgrade today.
There used to be a flat white speaker icon with several ))) behind it to show the sound strength.
Now everything is oddly coloured and there's some stupid bar that goes up? And the Crunchbang icons just won't show at all. The Oxygen icons also redirect to elementary Xubuntu dark.
![screenshot_2016-02-04_12-56-32](https://cloud.githubusercontent.com/assets/7514912/12814403/1736d3f6-cb3f-11e5-9084-f3ca49f22302.png)
![screenshot_2016-02-04_12-57-05](https://cloud.githubusercontent.com/assets/7514912/12814405/18dbe156-cb3f-11e5-993f-99d878165982.png)
![screenshot_2016-02-04_12-57-24](https://cloud.githubusercontent.com/assets/7514912/12814406/1a66a326-cb3f-11e5-9797-1a87aa18d980.png)
![screenshot_2016-02-04_12-57-44](https://cloud.githubusercontent.com/assets/7514912/12814407/1b7c0daa-cb3f-11e5-89ef-9875e6dff113.png)
![screenshot_2016-02-04_12-58-04](https://cloud.githubusercontent.com/assets/7514912/12814408/1c8ad7d0-cb3f-11e5-9c80-c783b1600270.png)
![screenshot_2016-02-04_12-58-38](https://cloud.githubusercontent.com/assets/7514912/12814409/1d84323a-cb3f-11e5-9d0c-fe1a4ee2e1b1.png)

**Comment by Makitk** [comment]
When changing the volume by rolling the scrollwheel over pnmixer's taskbar icon, the expected pop-up shows, with the icon I was expecting to see in the taskbar as well;
![screenshot_2016-02-04_13-01-22](https://cloud.githubusercontent.com/assets/7514912/12814451/730a5086-cb3f-11e5-87b2-f061556b6d2a.png)

**Comment by elboulangero** [comment]
Hi, about the vertical bar showing on the icon, just uncheck the "Draw Volume Meter" option. For the icon I have no idea at the moment. How big was your system upgrade ?

**Comment by Makitk** [comment]
10~15 packages, nothing new considering I have backports and testing in my sources.

**Comment by elboulangero** [comment]
Hi, I also remember that in CrunchBang, the default icon was the white icon you mentioned, with the ))). But this is not the default PNMixer icon and has never been. I don't know why it was the default on Crunchbang, I think they patched the default PNMixer config to select the icon theme they liked by default.

I actually use the white icon you mention. On my laptop I can get it in two icon themes: Faenza and Vibrancy. I uninstalled the Cruchbang stuff for a long time now, so I don't have the Crunchbang icon theme anymore.

I also remember struggling with that at some point, and I remember that I had a weird icon size configured in Tint2, and this caused problems. Can you check your tint2rc and tell me what's your current icon size (probably in `~/.config/tint2/tint2rc`, look for `systray_icon_size`).

**Comment by Makitk** [comment]
systray_icon_size = 24

Installing bunsen-faenza-icon-theme and setting pnmixer to use Faenza-Dark-Bunsen fixed it.

**Comment by elboulangero** [comment]
Ok nice, thx for the feedback !
