### ISSUE TITLE
Release 0.7

### ISSUE THREAD

**Issue by elboulangero** [nicklan/pnmixer#123]
That's it, I'd be happy to release a new version with the new PNMixer code.

**Comment by hasufell** [comment]
I wonder if we should rather do 0.6.2... 0.7 gives a feeling of new features, while this is mainly code refactoring

**Comment by elboulangero** [comment]
And 0.6.2 gives me a feeling of bugs fixed, while this is probably... bugs created ;)
I will review the changes that happened since 0.6 and sum that up in the Changelog so that we have a better view of what happened lately

**Comment by elboulangero** [comment]
Hi ! I updated the Changelog on my branch, to me there's quite a few change, making a new major version seems just like the logical thing to do. Have a look at the commit here:
https://github.com/elboulangero/pnmixer/commit/674c4a8af01cf3768a6852577409ddbac7bb26a3

**Comment by hasufell** [comment]
a documentation warning:
```
/home/jule/git/pnmixer/src/audio.c:430: warning: argument 'volume' of command @param is not found in the argument list of _audio_set_volume(Audio *audio, AudioUser user, gdouble cur_volume, gdouble new_volume, gint dir)
/home/jule/git/pnmixer/src/audio.c:439: warning: The following parameters of _audio_set_volume(Audio *audio, AudioUser user, gdouble cur_volume, gdouble new_volume, gint dir) are not documented:
  parameter 'cur_volume'
  parameter 'new_volume'
```

relevant code:
```
/**
 * Set the volume.
 *
 * @param audio an Audio instance.
 * @param user the user who performs the action.
 * @param volume the volume value to set, in percent.
 * @param dir the direction for the volume change
 *        (-1: lowering, +1: raising, 0: setting).
 */
void
_audio_set_volume(Audio *audio, AudioUser user, gdouble cur_volume,
                  gdouble new_volume, gint dir)
```

**Comment by hasufell** [comment]
We should also add `doxygen graphviz` as dependencies for building the documentation to README.md.

**Comment by elboulangero** [comment]
Done

**Comment by hasufell** [comment]
I guess you can create the PR now. Is there anything that has changed for packagers except the tighter gtk+:3 version constraint?

**Comment by elboulangero** [comment]
I think there's only Gtk version, you're right.

**Comment by elboulangero** [comment]
PR created, waiting for Travis to do its job

**Comment by elboulangero** [comment]
Ok, I contacted the TP for translation, it's in progress. People out there, feel free to use and test PNMixer like crazy. When the translations will be done, we can make a release, no need to wait I think.

**Comment by elboulangero** [comment]
Btw, lately I changed my Gtk theme, and I noticed that a few things were broken in the UI, in the prefs dialog. It was not visible with my previous theme. So I fixed that. It would be good if other people could give it a quick look, just to be sure the UI looks OK with their theme.

**Comment by elboulangero** [comment]
Ok, I imported translations from the TP. Result: 4 new translations ! But none of the existing translations were updated...

Through Github though, we had Chinese and Russian translations updated.

So, we're left with 3 translations to update: French, German and Italian. I'll take care of the French. @hasufell, you want to do the German ? As for the Italian, well I guess we will just let it like that.

**Comment by hasufell** [comment]
> you want to do the German ?

Maybe, but I have a change of job, so not sure if I can get to it in time.

**Comment by elboulangero** [comment]
Oh, I just received the German translation on the TP: <http://translationproject.org/latest/pnmixer/de.po> Lucky you !

**Comment by elboulangero** [comment]
Ok, almost ready to release, just waiting for #127 and #136

**Comment by elboulangero** [comment]
OK to release it seems to me

**Comment by hasufell** [comment]
what about #136 ?

**Comment by elboulangero** [comment]
I really think it's not a PNMixer bug, so I would just let it be. I mean, I'd let the ticket report open, and just remove it from the 0.7 milestone...

**Comment by elboulangero** [comment]
I cooked a little test that shows the bug, so definitely not a PNMixer bug to me.

    git clone https://github.com/elboulangero/gtk-status-icon-size-test.git

**Comment by hasufell** [comment]
can we nail it down to a function? I mean which function behaves differently in terms of gtk2 vs gtk3?

**Comment by elboulangero** [comment]
I believe it's the code that resize the PNG and display it. It happens somewhere when we assign the PNG, through `gtk_status_icon_set_from_file()` in this example, or `gtk_status_icon_set_from_pixbuf()` in PNMixer.

**Comment by hasufell** [comment]
The icons (without the vol_meter) look different for gtk2 and gtk3, although they are from the same file:
gtk2:
![gtk2](https://cloud.githubusercontent.com/assets/1241845/18562136/d18137b2-7b82-11e6-827a-bb0281116e3c.png)
gtk3:
![gtk3](https://cloud.githubusercontent.com/assets/1241845/18562149/dc107e36-7b82-11e6-8d15-a09264f33d15.png)

There seems to be more space to the left for the gtk2 icon.

**Comment by elboulangero** [comment]
Yep the Gtk3 icon seems to be a bit bigger...

Anyway, do we release ?

**Comment by hasufell** [comment]
I'm doing some testing now and then we should release

**Comment by hasufell** [comment]
I think we are ready

**Comment by hasufell** [comment]
All that's left now should be to create the actual release on the release page.
