### ISSUE TITLE
make Device the first tab in Prefs

### ISSUE THREAD

**Issue by landroni** [nicklan/pnmixer#127]
It always felt to me like the Device tab in Prefs should be the first one in the list, followed by View and all the other. If people need to change the device often (add USB DAC, connect HDMI, etc.), then it would make sense to make the Device choices handy. View on the other hand is something you would set up once and forget about it... 

Originally discussed here: 
https://github.com/nicklan/pnmixer/issues/100#issuecomment-193692673

**Comment by elboulangero** [comment]
I'm OK with that, it seems wise to me.

**Comment by elboulangero** [comment]
I'll merge that if nobody's against
