### ISSUE TITLE
Fix compilation with --whithout libnotify in version 7.0

### ISSUE THREAD

**Issue by Kal42** [nicklan/pnmixer#132]
With version 7.0, you should not include the libnotify header in notify.c, if libnotify is not use.

Here is the patch :
[0001-fix-header-notif_c.txt](https://github.com/nicklan/pnmixer/files/309015/0001-fix-header-notif_c.txt)

Best regards,

**Comment by hasufell** [comment]
can you make a real pull request?

**Comment by Kal42** [comment]
Done.

**Comment by hasufell** [comment]
https://github.com/nicklan/pnmixer/commit/8067fa38a7b097c3dffcb74bea80d9b6bcde32f6

**Comment by elboulangero** [comment]
Thanks !
