### ISSUE TITLE
Debian?

### ISSUE THREAD

**Issue by Makitk** [nicklan/pnmixer#134]
I like pnmixer. CrunchBang used pnmixer. They had their own repository and had pnmixer debs in there.
CrunchBang is dead. BunsenLabs was pushed up as a community-continuation.
BunsenLabs has no repository of its own, and makes no .deb available for pnmixer.

Rather than using pnmixer, they have resorted to using Volti.

Volti has merit on its own, but when I use my scrollwheel to run the volume up or down in pnmixer, I get a proper notification pop-up where I have set it to pop up. Volti has trouble with notifications.

Volti has trouble with some other things as well. I'm really not too impressed with it.

So here's me hoping pnmixer could offer up a way I could install it more easily than with tarballs since I keep having headaches when I need to do source-builds.

If you can run a deb or get the bloody debian team to drop it in their repos for Deb8, that would be lovely...

**Comment by hasufell** [comment]
https://packages.debian.org/search?keywords=pnmixer

**Comment by Makitk** [comment]
Can't find it in the list when I search for it through apt or synaptic.

Sources:
deb http://http.debian.net/debian wheezy main contrib non-free
deb http://http.debian.net/debian jessie main contrib non-free
deb http://http.debian.net/debian jessie-updates main
deb http://security.debian.org/ wheezy/updates main
deb http://security.debian.org/ jessie/updates main
deb http://http.debian.net/debian wheezy-backports main contrib non-free
deb http://http.debian.net/debian jessie-backports main contrib non-free

What am I missing here?

**Comment by Makitk** [comment]
Oh, testing. Yeah, I don't have testing in my sources.

**Comment by Makitk** [comment]
It's not that I'm dumb; I just overlook some things. Dumped testing in the sources, installed pnmixer, removed testing from the sources. Closing this thingie.
