### ISSUE TITLE
Extraneous newline in notification summary

### ISSUE THREAD

**Issue by aminb** [nicklan/pnmixer#147]
Is the `\n` in the end of the notification summary intentional?

https://github.com/nicklan/pnmixer/blob/7a1b71c5ebeab6795c866ebb6e7bd88275a910a5/src/notif.c#L79

It makes the notifications look out of place in dunst.

**Comment by elboulangero** [comment]
Hi, I think it's a mistake. I actually never saw these lines. What I see with my setup is an icon and a volume slider.

![pnmixer-0 7-noti](https://cloud.githubusercontent.com/assets/1942580/18770425/d6783b3e-815f-11e6-8cf4-9baa53425f03.png)

**Comment by aminb** [comment]
Hi @elboulangero,

That makes sense, since `xfce4-notifyd` shows a progress bar and no text summary.

This however is what I see with `dunst`:

![pnmixer-notif](https://cloud.githubusercontent.com/assets/1254858/18771147/81ff8828-810a-11e6-923a-01f0657ce5ba.png)

And this is a normal notification for reference (no extra `\n` in the end):

![brightness-notif](https://cloud.githubusercontent.com/assets/1254858/18771167/b23ffbda-810a-11e6-9656-195e06863f51.png)

**Comment by elboulangero** [comment]
Cool, thanks for the feedback and screenshots. Fixed by commit 5f6c1701355478df2e79c4716bfdb836c475d527.

**Comment by aminb** [comment]
Cheers :beers:
