### ISSUE TITLE
pnmixer does not react for default device change - restart required

### ISSUE THREAD

**Issue by carbolymer** [nicklan/pnmixer#150]
**Steps to reproduce:**
1. Open volume control (I'm using `pavucontrol`)
2. Select other device as "fallback"
3. Change volume on pnmixer (using hotkeys, slider or mouse scroll)

**Expected behaviour:**
Volume of newly selected device is adjusted

**Actual behaviour:**
Volume of previously chosen device is adjusted. Restart of pnmixer is required to make the change visible.

**Comment by hasufell** [comment]
Shouldnt `Reload Sound` be enough? Are you using pulseaudio?

**Comment by carbolymer** [comment]
Right. This option is enough. :)
