### ISSUE TITLE
rework travis build

### ISSUE THREAD

**Issue by hasufell** [nicklan/pnmixer#155]
The docker infrastructure somewhat sucks. I have to update the images manually etc. Needs to be reworked somehow.

**Comment by elboulangero** [comment]
By the way, I was wondering, do you see this kind of errors sometimes when pulling an image from Docker Hub ?

    Pulling repository docker.io/elboulangero/goodvibes-ubuntu
    Tag latest not found in repository docker.io/elboulangero/goodvibes-ubuntu

I got this kind of errors from times to times. I don't know who to blame !

**Comment by hasufell** [comment]
From within travis? Travis has trouble when too many jobs are running and docker pulls might get killed. Other than that: docker in general is rather unreliable.

**Comment by elboulangero** [comment]
Well I don't use Travis, I use Shippable (an equivalent). And I see that from within Shippable. I was wondering if it also happens in Travis or not. I have no idea whose to blame here.

**Comment by hasufell** [comment]
Only building on debian:testing now, limited build matrix, so we don't get 30+ minutes builds. This should suffice anyway.
