### ISSUE TITLE
release 0.7.1

### ISSUE THREAD

**Issue by hasufell** [nicklan/pnmixer#156]

**Comment by elboulangero** [comment]
Code is ready for this minor version to me. I want to package that asap since after that I really, really won't have time for PNMixer.

**Comment by hasufell** [comment]
Latest merges broke the build on exherbo (and probably gentoo). Those don't use `autoreconf`, but call things manually. It seems one must run `gettextize` too, but that changes configure.ac and then the build fails too.

**Comment by hasufell** [comment]
* build system switched
* travis fixed
* ChangeLog updated

**Comment by hasufell** [comment]
I also think we should cryptographically sign the release tarball.

**Comment by hasufell** [comment]
https://github.com/nicklan/pnmixer/releases/tag/v0.7.1
