### ISSUE TITLE
pnmixer crashes if you don't set the three hotkeys when hotkeys are enabled

### ISSUE THREAD

**Issue by 00cpxxx** [nicklan/pnmixer#159]
Hi, thanks for pnmixer. I really enjoy it. I just noticed that after configuring only volume UP and DOWN, leaving the mute unset pnmixer will crash. The small change below solves the problem.

<pre>diff --git a/src/hotkey.c b/src/hotkey.c
index 2ac6abe..82193ef 100644
--- a/src/hotkey.c
+++ b/src/hotkey.c
@@ -135,7 +135,7 @@ hotkey_matches(Hotkey *hotkey, guint code, GdkModifierType mods)
 {
        guint i;
 
-       if (code != hotkey->code)
+       if (!hotkey || code != hotkey->code)
                return FALSE;
 
        for (i = 0; i < G_N_ELEMENTS(keymasks); i++)
<pre>

**Comment by elboulangero** [comment]
Nice catch, thanks for that. Fix commited.
