### ISSUE TITLE
support for older glib/gtk

### ISSUE THREAD

**Issue by Milozzy** [nicklan/pnmixer#16]
Dear nicklan,

I am unable to compile pnmixer 0.5.1 (but had the same issue with 0.5.0) on Debian Squeeze, both 32 and 64 bit.

Running ./autogen.sh works fine, but when go on with make it fails with these errors:

$ make
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/milo/Scaricati/pnmixer-0.5.1/missing --run autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/bash ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-recursive
make[1]: Entering directory `/home/milo/Scaricati/pnmixer-0.5.1'
Making all in src
make[2]: Entering directory `/home/milo/Scaricati/pnmixer-0.5.1/src'
gcc -DHAVE_CONFIG_H -I. -I.. -DPACKAGE_DATA_DIR=\""/usr/local/share"\" -DPACKAGE_LOCALE_DIR=\""/usr/local/share/locale"\" -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/alsa     -O2 -export-dynamic  -MT support.o -MD -MP -MF .deps/support.Tpo -c -o support.o support.c
mv -f .deps/support.Tpo .deps/support.Po
gcc -DHAVE_CONFIG_H -I. -I.. -DPACKAGE_DATA_DIR=\""/usr/local/share"\" -DPACKAGE_LOCALE_DIR=\""/usr/local/share/locale"\" -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/alsa     -O2 -export-dynamic  -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
mv -f .deps/main.Tpo .deps/main.Po
gcc -DHAVE_CONFIG_H -I. -I.. -DPACKAGE_DATA_DIR=\""/usr/local/share"\" -DPACKAGE_LOCALE_DIR=\""/usr/local/share/locale"\" -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/alsa     -O2 -export-dynamic  -MT hotkeys.o -MD -MP -MF .deps/hotkeys.Tpo -c -o hotkeys.o hotkeys.c
mv -f .deps/hotkeys.Tpo .deps/hotkeys.Po
gcc -DHAVE_CONFIG_H -I. -I.. -DPACKAGE_DATA_DIR=\""/usr/local/share"\" -DPACKAGE_LOCALE_DIR=\""/usr/local/share/locale"\" -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/alsa     -O2 -export-dynamic  -MT alsa.o -MD -MP -MF .deps/alsa.Tpo -c -o alsa.o alsa.c
mv -f .deps/alsa.Tpo .deps/alsa.Po
gcc -DHAVE_CONFIG_H -I. -I.. -DPACKAGE_DATA_DIR=\""/usr/local/share"\" -DPACKAGE_LOCALE_DIR=\""/usr/local/share/locale"\" -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/alsa     -O2 -export-dynamic  -MT callbacks.o -MD -MP -MF .deps/callbacks.Tpo -c -o callbacks.o callbacks.c
mv -f .deps/callbacks.Tpo .deps/callbacks.Po
gcc -DHAVE_CONFIG_H -I. -I.. -DPACKAGE_DATA_DIR=\""/usr/local/share"\" -DPACKAGE_LOCALE_DIR=\""/usr/local/share/locale"\" -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/alsa     -O2 -export-dynamic  -MT prefs.o -MD -MP -MF .deps/prefs.Tpo -c -o prefs.o prefs.c
mv -f .deps/prefs.Tpo .deps/prefs.Po
gcc -O2 -export-dynamic    -o pnmixer support.o main.o hotkeys.o alsa.o callbacks.o prefs.o -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lm -lpangocairo-1.0 -lcairo -lgio-2.0 -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0 -lasound    -lm -lX11 
alsa.o: In function `card_free':
alsa.c:(.text+0xce): undefined reference to `g_slist_free_full'
alsa.o: In function `get_cards':
alsa.c:(.text+0x2ee): undefined reference to `g_slist_free_full'
collect2: ld returned 1 exit status
make[2]: *** [pnmixer] Error 1
make[2]: Leaving directory `/home/milo/Scaricati/pnmixer-0.5.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/milo/Scaricati/pnmixer-0.5.1'
make: *** [all] Error 2

Thank you very much in advance for any reply and feel free to ask any additional information.

Best Regars

Marco Milone

**Comment by hasufell** [comment]
I think we can move on.

**Comment by mckaygerhard** [comment]
u cannot close! due u dont put any commit that fixed the issue!

i upload a package but only for debian! https://groups.google.com/d/msg/venenuxsarisari/rJfuZmit0mQ/BQGwh2i5YZkJ

u must understand that why i compile a minimal tool if the machines today has large amount of RAM and CPU cycles!

so then this king of tools like pnmixer are for older hardware and older hardware only runs good older distros and older software!

**Comment by elboulangero** [comment]
Hello,

from my experience, maintaining compatibility with old libraries (gtk2 2.18 is 6 years old) is painful and time consuming. I have no interest and no time for that.

This being said, if it's just a matter about `g_slist_free_full()`, why don't you fork PNMixer, prepare a clean commit, and ask for a pull request ? From your previous messages, you already fixed the problem and got PNMixer to work with your config, so just share your patch.

As far as I'm concerned, if the patch is trivial, there's no reason not to include it. But I'm not going to make this patch, to test it against old glib and old gtk, and debug it all the way. If you want such backward compatibility, you're on your own with that. And it's likely that you will have some patch to make to preserve backward compatibility in PNMixer 0.7, then 0.8 and so on. While it's trivial, it's OK. And it's also likely than one day, a good portion of the code will rely on new stuff from GLib, and that you will need to rewrite this whole part of the code for old GLib. Such a patch won't be accepted, as far as I'm concerned.

In the long run, you just can't run latest version of a software with an old distribution. With time you will have to either stick with old software too, or change your distrib, and choose one which targets low-resource machines (something else than Debian).

In the short-term, if your patch is trivial, just send it.

**Comment by hasufell** [comment]
> This being said, if it's just a matter about g_slist_free_full(), why don't you fork PNMixer, prepare a clean commit, and ask for a pull request ?

Yes, I have been waiting for that since half a year. If there is no action... then that means closed, I am afraid.
