### ISSUE TITLE
static analyzer issues

### ISSUE THREAD

**Issue by hasufell** [nicklan/pnmixer#174]
Fixed the build with the clang analyzer and it found a few issues:

* [potential memory leak](https://travis-ci.org/nicklan/pnmixer/jobs/343041284#L3795) which was easy to fix
* [possible garbage value](https://travis-ci.org/nicklan/pnmixer/jobs/343041284#L3832) which is caused by `tray_icon_reload()` it seems, but I'm not sure exactly why, any ideas?

**Comment by elboulangero** [comment]
> possible garbage value which is caused by tray_icon_reload() it seems, but I'm not sure exactly why, any ideas?

I created a branch with this commit: https://github.com/nicklan/pnmixer/commit/c02c1bd8e22fa07422f2c0d23cb5e59fbc3c10b1

However after your PR #175 I think it's not relevant anymore, you fixed it there already. If Clang is all happy then I'll just delete my branch.
