### ISSUE TITLE
New improved translation in Crotatian

### ISSUE THREAD

**Issue by boput** [nicklan/pnmixer#176]
Hi, I have just submitted new improved translation to Translation project:
Quote of the acceptance from the Translation Project Robot:
Hi!  I am the service robot at the Translation Project,
and was awakened by your submission of 'pnmixer-0.7.1-rc3.hr.po'.

Your file has been accepted and stored in the archives.  Thank you!

                                The Translation Project robot, in the
                                name of your kind translation coordinator.
                                <coordinator@translationproject.org>
Unquote:
Kindly replace the old translation with the new one. Thanks.

Best,

Božidar

**Comment by elboulangero** [comment]
Updated in a459729, thanks!
