### ISSUE TITLE
PNmixer Window draws below floating tint2 bar

### ISSUE THREAD

**Issue by bitthegeek** [nicklan/pnmixer#31]
I am using a floating tint2 bar and conky for the "bar"'s background. However, clicking on the systray icon, pnmixer instead prefers to go below the floating tint2 bar making it unusable.

Should it honor the tray location when it shows up its volume control window?

Please see images below:
PNmixer closed:
![screenshot - sunday 15 september 2013 - 12 38 49 pht](https://f.cloud.github.com/assets/2142586/1144700/5996065a-1dc1-11e3-9ad4-14307db9db00.png)

PNmixer open:
![screenshot - sunday 15 september 2013 - 12 39 29 pht](https://f.cloud.github.com/assets/2142586/1144701/630df0b2-1dc1-11e3-87b8-6167ecd164fe.png)

I'm using PNMixer 0.5.1 on Debian Linux btw.

**Comment by elboulangero** [comment]
Hi, I also use tint2 (and openbox as a window manager), and I don't have any issue. What do you call a "floating" tint2 ? Which tint2 version ? Maybe you can send me your tint2rc so that I try to reproduce the problem ?

**Comment by hasufell** [comment]
Not enough info. We can reopen if there is info.
