### ISSUE TITLE
Volume icons

### ISSUE THREAD

**Issue by ghost** [nicklan/pnmixer#32]
When selecting an icon theme in pnmixer settings, pnmixer is going to look for volume icons named:
pnmixer-high
pnmixer-medium
pnmixer-low
pnmixer-muted
But because most of the themes have volume icons named:
audio-volume-high
audio-volume-medium
audio-volume-low
audio-volume-muted
, pnmixer will fall back to default theme.
Can't it search like this: Search for pnmixer-* icons, if they aren't there, search for audio-volume-* icons. Else, fallback to default icons?
EDIT: I see that it does this in main.c, but for some reason it fails. After symlinking the audio-volume-* icons to pnmixer-*, correct icons started displaying.

**Comment by elboulangero** [comment]
Is it still an issue ? I see on the code that PNMixer looks for icons named `audio-volume-*`, except if no icon them is selected, in this case it looks for its own icon set named `pnmixer-*`. I think this should be closed. I personnally never had any issue with that. I just tested it again and it works ok.

**Comment by elboulangero** [comment]
I close that, I believe it's been fixed for a while
