### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by hasufell** [nicklan/pnmixer#48]
I did that on my own branch, pretty straight forward:
c57af39a0e350218ac93bc147b8b2e99c8484168
ee525011070412be04ef3c3a07a7f75d0f638a94

Ofc the README.md has to point to the correct travis page, not the one in that commit.

https://travis-ci.org/hasufell/pnmixer

**Comment by nicklan** [comment]
Okay PR #64 takes care of this.  I did have to reduce the version of gtk that we depend on, so if there was a strong reason we needed 3.6.0 rather than 3.4.2, we shouldn't merge, but I couldn't find any reason that shouldn't work.

**Comment by nicklan** [comment]
Fixed by PR #64
