### ISSUE TITLE
release 0.6

### ISSUE THREAD

**Issue by hasufell** [nicklan/pnmixer#65]
@nicklan is there anything important left or should we just throw out a new release. People keep filing bugs against the 0.5 release which are long fixed.

**Comment by nicklan** [comment]
Yeah, we probably should.  I'll get on that this week.  Thanks for poking me :)

**Comment by hasufell** [comment]
I think we just need to update the translation stuff and then we are good to go.

**Comment by elboulangero** [comment]
About translation: there's a file that bothers me, `po/Makefile.in.in`. This file is versionned, and is modified when I run `autogen.sh`. After some investigation, this file is copied by the command `glib-gettextize --force --copy`, and it comes directly from `glib2` (`/usr/share/glib-2.0/gettext/po/Makefile.in.in`on my system).
Since `glib2` is a build dependency, is there any reason to version this file ? Shouldn't we just remove it ?

**Comment by hasufell** [comment]
7bd4b3cf712eb96aa5bf98ef6d314816668cac28

**Comment by elboulangero** [comment]
Hi,
I just pushed a new branch to work on the translations. Since it's my very first time with translations and gettext and all that stuff, I don't really know what I'm doing :smile: Please have a quick look.

I'm not so sure about 23f8c3c, maybe renaming files was not needed. But for the rest it's pretty straight-forward, I just fixed a few strings here and there, updated translations files with `make -C po update-po`, then completed the french translation.

**Comment by landroni** [comment]
One minor consideration: updating the copyright year. Now it states: 

    Copyright © 2010-2011 Nick Lanham

**Comment by hasufell** [comment]
tagged a release candidate since everything else should just be cleanup, whitespace, translation and co

https://github.com/nicklan/pnmixer/releases/tag/v0.6_rc1

**Comment by elboulangero** [comment]
OK, I did a bit of work, eventually merged the translation branch back into master, and created a v0.6-rc2 tag. I sent a mail to the TP with the URL of the archive. Wait and see now

**Comment by elboulangero** [comment]
I had a reply from the Translation Project, I'm discussing the matter with the coordinator, but I need @nicklan to be part of the discussion, as he's the owner of the project. Basically, the question is whether we want to hand over translation to the TP or not. @nicklan, can you please send me your private email, so I add you to the email discussion that's going on wit the TP ?

**Comment by elboulangero** [comment]
I pushed an updated Changelog for 0.6, feel free to improve it

**Comment by elboulangero** [comment]
I finally received russian translation from Pavel. So all translations are OK, I did some indentation, tagged that as v0.6-rc3. Everything OK for a release, everyone can test a little bit more if he wants.

**Comment by elboulangero** [comment]
One last word about translations, for the next 0.7 version we will probably do it through TP (Translation Project), as it has been discussed already. I will send a mail to the people concerned about that when it's needed.

**Comment by hasufell** [comment]
Wrt style and indenting: indenting is not consistent. We still have mixed spaces and tabs and in some places more spaces/tabs are used than in others. Maybe we should fix that. I'd personally vote for tabs. Deleting all the whitespaces can be annoying and two spaces indenting is sometimes tricky to read.

**Comment by elboulangero** [comment]
About whitespaces: I don't care much about that, since PNMixer is indented with two spaces from the beginning, I just let it be like that. Now if we have to change that, my usual coding style is roughly the style used in kernel: tab indenting, no space after procedure call, space before a cast... If we agree on that, we can indent all the code with the `indent` command. For example, have a look at the code after `indent --linux-style -psl -cs -l100 ./src/*.[ch]` and tell me what you think. `indent` is not perfect, but I don't know a better tool for that.

**Comment by hasufell** [comment]
Yep, that's what I was thinking too. https://github.com/nicklan/pnmixer/pull/96

**Comment by elboulangero** [comment]
AUTHORS updated

**Comment by hasufell** [comment]
Also, that README symlink is annoying. Distro PMs will often install both, although the content is the same.

Since autotools is bitchy about removing `README`, we could just add `AM_INIT_AUTOMAKE([foreign])` to configure.ac.

**Comment by elboulangero** [comment]
Hmm, not sure but maybe GitHub is happy enough if there's only a README file. Maybe it autodetects the markdown format anyway. I'll try.

**Comment by hasufell** [comment]
Well, it is markdown, so `README.md` makes sense.

**Comment by elboulangero** [comment]
Yep you're right. Let's go for `foreign`.

**Comment by hasufell** [comment]
https://travis-ci.org/nicklan/pnmixer/jobs/78361590#L407

seems the removal of NEWS also caused trouble, `foreign` should fix that too

**Comment by elboulangero** [comment]
:)

**Comment by hasufell** [comment]
So, seems we are set, should I push the tag?

**Comment by elboulangero** [comment]
Yep !

**Comment by elboulangero** [comment]
Oh wait !

**Comment by hasufell** [comment]
WAH TOO LATE

**Comment by elboulangero** [comment]
NOOOO !

**Comment by hasufell** [comment]
:(((((

**Comment by elboulangero** [comment]
The tarball generated miss some files, because of the `foreign` flag.

**Comment by elboulangero** [comment]
Hmmm, I think only the README.md must be added expicitely.

**Comment by hasufell** [comment]
you mean for `make dist`?

**Comment by elboulangero** [comment]
yep

**Comment by hasufell** [comment]
```
@@ -1,11 +1,11 @@
 ## Process this file with automake to produce Makefile.in
 
 SUBDIRS = data po src
 
 EXTRA_DIST = \
-	autogen.sh
+	autogen.sh README.md
 
 dist-hook:
 	$(MAKE) -C "$(srcdir)/po" "$(GETTEXT_PACKAGE).pot"
 	cp "$(srcdir)/po/$(GETTEXT_PACKAGE).pot" "$(distdir)/po/"
 
```

**Comment by elboulangero** [comment]
Agreed

**Comment by hasufell** [comment]
I will retag (already that is very baaaaad, but I guess no one is depending on the hash yet).

**Comment by hasufell** [comment]
So, anything left? LAST TIME.

**Comment by hasufell** [comment]
maybe we should make it fancy, even https://github.com/blog/1547-release-your-software

**Comment by elboulangero** [comment]
The `INSTALL` file is not part of the tarball anymore. It's weird, because other standard files are included (like `AUTHORS` and `Changelog`)...

**Comment by hasufell** [comment]
Was that a question? :P

**Comment by elboulangero** [comment]
No it's OK, I just noticed that the `INSTALL` file is not created at all with the `foreign` flag, therefore it's normal that it's not in the tarball.
So I'm OK to retag !

**Comment by hasufell** [comment]
https://github.com/nicklan/pnmixer/releases

**Comment by elboulangero** [comment]
> maybe we should make it fancy

Let me have a look. Actually I already made a release with PNMixer some time ago, by mistake :) I wanted a tarball for the translators to download. But then I noticed that each time you create a tag, Github creates an URL to download a tarball for this tag, so using the Github release feature was useless. So I un-released :)

**Comment by elboulangero** [comment]
> https://github.com/nicklan/pnmixer/releases

Cool !

**Comment by hasufell** [comment]
Theoretically we could have added binaries, but I am personally against that. Too error prone.

**Comment by hasufell** [comment]
done

**Comment by elboulangero** [comment]
Yep. But you see, this is where we can attach a tarball created with `make dist`. The difference with the tarball generated by github is that the one with make dist contains the pot file. It's not needed right now, but for the next release I'd like to give a try to the TP for translating, and I will need a placeholder for the dist tarball that the TP guys need. I think I'll use this 'release' feature just for that.

**Comment by hasufell** [comment]
Well, you can make a `0.6.1` release then. Distributors can just skip it.

**Comment by elboulangero** [comment]
Yep. Anyway, we're done with this 0.6, nice job ! See you soon for the 0.7 :)

**Comment by hasufell** [comment]
cheers :beers:

**Comment by landroni** [comment]
I notice that https://github.com/nicklan/pnmixer/archive/v0.6.tar.gz doesn't include a `configure` file (i.e. it seems a snapshot of GIT). Is this intentional? 

I ask because usually projects run `autogen.sh` before packing the release, so I'm wondering if this is an omission...

**Comment by hasufell** [comment]
I'm not very familiar with the github release workflow. I assumed that releases are _always_ tags (with an optional addition of a binary package). No?

**Comment by landroni** [comment]
I'm not overly familiar with github releases either, but here's what I notice with other GIT projects. Take Thunar in Xfce. It has a tag: 
http://git.xfce.org/xfce/thunar/tag/?id=thunar-1.6.10

associated to a snapshot of GIT: 
http://git.xfce.org/xfce/thunar/snapshot/thunar-1.6.10.tar.bz2

This is the same as what pnmixer now has. But there is also a source archive that is the actual release proposed to end-users and package managers: 
http://archive.xfce.org/src/xfce/thunar/1.6/
http://archive.xfce.org/src/xfce/thunar/1.6/Thunar-1.6.10.tar.bz2

This one is *not* a snapshot of GIT, and contains among other things a `configure` file. Roughly same happens at LyX. 

In my packaging experience, projects do not expect end users to have all the tools needed to run `autogen.sh`: a source package---the release---will contain a `configure` file; if a package comes with only `autogen.sh`, then chances are high that it's merely a development snapshot. For instance debian packaging tools by default do not attempt `autogen.sh` but go for configure instead; if the latter is missing, the toolchain will fail. (This is rather easy to fix, but I think points to the convention of development snapshot vs source release.)

**Comment by hasufell** [comment]
I don't think github provides this feature (if you can prove me wrong, the better!). You'd have to cross-host your project on sourceforge or (which I won't do) commit the `configure` file in the repository (spacefm does that). In the early days of github there was the possibility to upload a random archive (similar to sourceforge). But that is gone.

Btw. I'm a packager myself (but for gentoo) and ofc we don't use `autogen.sh` there either, but I expect packagers to know what they are doing.

**Comment by landroni** [comment]
Cross-hosting is a generally confusing for users, and including `configure` in the repo is undesirable. 

What could be done, however, is to create a branch explicitly for a release where you do include the `configure`. This branch would stay forever detached from master, and be tagged for the release? Can this be done, or do tags work only for master? 

Otherwise, can we leverage the Attach Binaries feature to attach a `tar.bz2` or similar of the release archive (which contains `configure`)?

**Comment by hasufell** [comment]
> What could be done, however, is to create a branch explicitly for a release where you do include the

Yeah, that's possible, however... I don't want to recreate the current tag, since that can break source distro packages that already depend on the hash (I know it would in gentoo). I could create another release named something like `0.6-autotools`? @elboulangero ? `0.6.1` doesn't make sense to me, because there is no bugfixing involved.

**Comment by elboulangero** [comment]
Well, I tried to attach the tarball archive as a binary file. It looks good, I mean, the link is clearly visible on the page: https://github.com/nicklan/pnmixer/releases. And it has a permanent link: https://github.com/nicklan/pnmixer/releases/download/v0.6/pnmixer-0.6.tar.gz. Don't you think it's OK like that ?

**Comment by landroni** [comment]
@elboulangero Looks good. 

*0.6.1  doesn't make sense to me, because there is no bugfixing involved.*
@hasufell If the release were 0.6.0, then a minor release of 0.6.0.1 would have been OK. But as it is, I agree with you. 

This separate branch approach may be useful for future release; don't think there is need to overly complicate things now. And if the attached "binary" is sufficient, then no need for this at all.

**Comment by landroni** [comment]
I get an error when building the package, though, via dpkg machinery: 

    Making check in po
    make[2]: Entering directory `/home/geek/Build/PPA/pnmixer/ppa1/pnmixer-0.6/po'
    INTLTOOL_EXTRACT="/usr/bin/intltool-extract" XGETTEXT="/usr/bin/xgettext" srcdir=. /usr/bin/intltool-update --gettext-package pnmixer --pot
    rm -f missing notexist
    srcdir=. /usr/bin/intltool-update -m
    The following files contain translations and are currently not in use. Please
    consider adding these to the POTFILES.in file, located in the po/ directory.

    src/notify.c

    If some of these files are left out on purpose then please add them to
    POTFILES.skip instead of POTFILES.in. A file 'missing' containing this list
    of left out files has been written in the current directory.
    if [ -r missing -o -r notexist ]; then \
          exit 1; \
        fi
    make[2]: *** [check] Error 1
    make[2]: Leaving directory `/home/geek/Build/PPA/pnmixer/ppa1/pnmixer-0.6/po'
    make[1]: *** [check-recursive] Error 1
    make[1]: Leaving directory `/home/geek/Build/PPA/pnmixer/ppa1/pnmixer-0.6'
    dh_auto_test: make -j1 check returned exit code 2
    make: *** [build] Error 2
    dpkg-buildpackage: error: debian/rules build gave error exit status 2
    debuild: fatal error at line 1364:
    dpkg-buildpackage -rfakeroot -D -us -uc -b failed
    >debuild -b -us -uc (8259) returned '29'

I don't know if it's an error on my side or something wrong with the archive. The code itself builds fine up until it gets to the po files...

**Comment by elboulangero** [comment]
Building from the archive works fine for me. I get a different output when typing `make`:

    Making all in po
    make[1]: Entering directory '/home/art/tmp/pnmixer/pnmixer-0.6/po'
    file=`echo de | sed 's,.*/,,'`.gmo \
      && rm -f $file && /usr/bin/msgfmt -o $file de.po
    file=`echo fr | sed 's,.*/,,'`.gmo \
      && rm -f $file && /usr/bin/msgfmt -o $file fr.po
    file=`echo it | sed 's,.*/,,'`.gmo \
      && rm -f $file && /usr/bin/msgfmt -o $file it.po
    file=`echo ru | sed 's,.*/,,'`.gmo \
      && rm -f $file && /usr/bin/msgfmt -o $file ru.po
    make[1]: Leaving directory '/home/art/tmp/pnmixer/pnmixer-0.6/po'

**Comment by elboulangero** [comment]
*Making all* instead of *Making check*

**Comment by elboulangero** [comment]
However the error message makes sense, `notify.c` is missing in the POT file. Adding it solves the issue.

**Comment by elboulangero** [comment]
Can you try again with this new archive in the release page `pnmixer-0.6-reloaded.tar.gz` please ?

**Comment by landroni** [comment]
Yes, thanks. Now debuild is happy.

**Comment by elboulangero** [comment]
So am I :)

**Comment by hasufell** [comment]
fascinating :wine_glass:

**Comment by elboulangero** [comment]
It pains me to say that, but I believe we're supposed to re-tag to something like 0.6.1, and attach the corresponding archive. We can't let an archive with such a name, `pnmixer-0.6-reloaded.tar.gz`... Or we can fall to the lure of the dark side, pretend that nobody noticed, and move the v0.6 tag a few commits ahead... Personally, I would shamelessly follow the dark side :smiling_imp: . And I will do that in a few seconds if nobody speaks against me

**Comment by hasufell** [comment]
> and move the v0.6 tag a few commits ahead

Please no. You have to create a new tag then. I have already committed something that depends on the checksum of the archive that is generated by the v0.6 tag. If you move it, things will break for the user and that might happen for other distros as well.

**Comment by landroni** [comment]
I would concur. Either the dark side, but if there are objections (and there seemed to be some above) then a 0.6.1 or a 0.6.0.1 is probably warranted...

**Comment by elboulangero** [comment]
@landroni So are you making a Debian package ? I'm a Debian user, but not a Debian dev at all, and I was thinking that maybe I could start learning how to create a Debian package, and try pushing it all the way to Debian offical repo somehow.

@hasufell OK

**Comment by hasufell** [comment]
> So are you making a Debian package ? I'm a Debian user, but not a Debian dev at all, and I was thinking that maybe I could start learning how to create a Debian package, and try pushing it all the way to Debian offical repo somehow.

Just use gentoo, it's better than debian. :package:

**Comment by elboulangero** [comment]
By the way, I never mentioned it, but I'm also a faithful Emacs user :smile:

**Comment by landroni** [comment]
I've now prepared an Ubuntu PPA for pnmixer: 
https://launchpad.net/~landronimirc/+archive/ubuntu/pnmixer

@elboulangero The debian packaging is basic, but works alright. You can use that as a base for Debian (reuse as is will likely work). 

For step-by-step Ubuntu/Debian packaging procedures see: 
https://github.com/OtterBrowser/otter-browser/issues/352#issuecomment-102004265

It would be nice (but hard, in my experience) to get pnmixer in Debian. Once that happens, Ubuntu will pick it up soon enough.

**Comment by landroni** [comment]
@elboulangero 

If you're working on this, start with the packaging for Trusty: 
https://launchpad.net/~landronimirc/+archive/ubuntu/pnmixer/+files/pnmixer_0.6.1-1~trusty~ppa2.debian.tar.gz

On Ubuntu Precise I had to revert to gtk2 because of lacking appropriate gtk3 version...

**Comment by hasufell** [comment]
> On Ubuntu Precise I had to revert to gtk2 because of lacking appropriate gtk3 version...

yeah, that's why the travis build fails too...

**Comment by elboulangero** [comment]
@landroni  Thanks for the explanations and links.

I saw that there's already a request to have PNMixer in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=745669. 500 days ago and no reply yet...

**Comment by landroni** [comment]
Yeah, that's my issue with both Debian and Ubuntu: the processes are too rigid given available manpower and manpower free time/interest. I think though it's worth renewing the request...

**Comment by elboulangero** [comment]
Hi ! I'm currently working on the Debian package. During the process I had to normalize a little bit the git tags of pnmixer, since Debian can automatically watch for new releases of the soft. But this works only if the tags or releases follow a certain naming. So I had to rename two tags, and you can now delete the old tag names from your local repo.

    git tag -d ver0.4
    git tag -d v0.6_rc1

**Comment by elboulangero** [comment]
@landroni

Hey, just to let you know that PNMixer made it to the official Debian repositories ! It's here:
<https://packages.debian.org/sid/pnmixer>

Thanks for providing links, it helped. In the process I wrote a step-by-step Debian packaging tutorial, in case you're interested it's available here:
<http://hacking.elboulangero.com/2016/01/14/debian-package-starting.html>

**Comment by hasufell** [comment]
my name is spelled wrongly: http://metadata.ftp-master.debian.org/changelogs/main/p/pnmixer/pnmixer_0.6.1-1_copyright

**Comment by elboulangero** [comment]
Oups, my bad, I made your name french :) I'll fix that in the next package version

**Comment by landroni** [comment]
Nice! Great job!
