### ISSUE TITLE
Improve Gtk3 Popup Window a little bit

### ISSUE THREAD

**Issue by elboulangero** [nicklan/pnmixer#67]
Currently there's no margin defined for the Gtk3 popup window, and the file popup_window-gtk3.xml is over-complicated and filled with unused stuff inherited from the Gtk2 version.

I reworked that a little bit with Glade too make it looks nicer. Attached a screenshot before modifications, and another after modifications.

If it looks OK to you, can I commit that ?

Before:
![popup-menu-gtk3-before](https://cloud.githubusercontent.com/assets/1942580/7101933/aeb4dec8-e06f-11e4-81b1-e29e9591fe1a.png)

After:
![popup-menu-gtk3-after](https://cloud.githubusercontent.com/assets/1942580/7101932/abf376cc-e06f-11e4-8249-f9c1c937ae90.png)

**Comment by hasufell** [comment]
> I reworked that a little bit with Glade too make it looks nicer.

You mean with the "IDE"? Or manually?

**Comment by elboulangero** [comment]
I mean that I used glade the IDE to edit popup_window-gtk3.xml. The good side is that I'm sure it produces a valid and up-to-date output, the bad side is that the diff is probably bigger (and harder to read) than if I edited manually.
Give me a few seconds to find how PR works, and I'll do that for sure :)

**Comment by elboulangero** [comment]
PR created. Actually the diff is not so big.
I realized that I removed all the popup menu in my first version, that's why I thought the diff was big, and that there was plenty of useless stuff in the XML file :D  But now I'm back to reality, and really it's just a minor change, it's just about adding margins around the main vbox.
