### ISSUE TITLE
Double clicking on popup window closes it [gtk2] [gtk3]

### ISSUE THREAD

**Issue by milos3** [nicklan/pnmixer#73]
The popup window closes when double clicking with left mouse button:
- gtk2: closes when double clicking on: blank space, volume slider, volume slider knob
- gtk3: closes when double clicking on: blank space, mute check box, volume slider, volume slider knob

**Comment by elboulangero** [comment]
I believe this behavior is not intended and can be considered as a bug. This was fixed by commit 47e5834, can you please pull the current git version and confirm ? Thanks

**Comment by hasufell** [comment]
I don't think we should hide the popup on unhandled events. I'm not sure why I added it in 50922db4 anyway.

**Comment by elboulangero** [comment]
The 'grab-broken-event' was handled here.

**Comment by hasufell** [comment]
Looks fixed to me.
