### ISSUE TITLE
Volume slider knob is beeing held when popup window is closed with double click [gtk2]

### ISSUE THREAD

**Issue by milos3** [nicklan/pnmixer#74]
1. When double clicking the volume slider it closes the popup window and the volume slider is still beeing held so the volume changes to 0% or 100% with 10% steps depending  if it was clicked left or right of the volume knob. Probably related to https://github.com/nicklan/pnmixer/issues/72 and https://github.com/nicklan/pnmixer/issues/73.

![4 1 1](https://cloud.githubusercontent.com/assets/5746405/7437697/2f3fe250-f05a-11e4-9e04-385fe2de4d95.gif)
2. When double clicking the volume slider knob it again closes the popup window and the volume now is still beeing held so next time when you open the popup window, the volume changes to the volume value which is parallel to the mouse cursor. Probably related to https://github.com/nicklan/pnmixer/issues/73

![4 1 2](https://cloud.githubusercontent.com/assets/5746405/7437699/33c8436c-f05a-11e4-8de9-8dec4d4df444.gif)

**Comment by elboulangero** [comment]
Fixed by commit 47e5834, please check and confirm. Thanks !

**Comment by hasufell** [comment]
Yep, works.
