### ISSUE TITLE
[Debian] libasound2-dev is required, not alsa-lib

### ISSUE THREAD

**Issue by dbb** [nicklan/pnmixer#78]
The dependencies in the README currently lists "alsa-lib", which in Debian is a *source package* rather than an actual package: https://packages.debian.org/source/sid/alsa-lib

So, if a user tries to install or search for "alsa-lib" they will see that there is no such package. Then, if they try `aptitude search "alsa lib"` it will show all packages with "alsa" and/or "lib" in the name like so:

```
p   libalsa-ocaml                               - OCaml bindings for the ALSA library                  
p   libalsa-ocaml-dev                           - OCaml bindings for the ALSA library                  
v   libalsa-ocaml-dev-w7mv8                     -                                                      
v   libalsa-ocaml-w7mv8                         -                                                      
p   libalsaplayer-dev                           - alsaplayer plugin library (development files)        
p   libalsaplayer0                              - alsaplayer plugin library                            
p   libclalsadrv-dev                            - ALSA driver C++ access library (development files)   
p   libclalsadrv2                               - ALSA driver C++ access library                       
p   libdssialsacompat-dev                       - DSSI ALSA compatibility library (development files)  
p   libdssialsacompat0                          - DSSI ALSA compatibility library for non-Linux platfor
p   libomxil-bellagio0-components-alsa          - ALSA source/sink components for Bellagio OpenMAX IL  
p   liboss4-salsa-asound2                       - OSS to Alsa compatibility library - binary compatibil
p   liboss4-salsa2                              - OSS to Alsa compatibility library                    
p   libsnack-alsa                               - Sound extension to Tcl/Tk and Python/Tkinter - ALSA f
v   libsnack2-alsa                              -                                                      
p   libsox-fmt-alsa                             - SoX alsa format I/O library                          
p   libzita-alsa-pcmi-dev                       - Development files (headers) for libzita-alsa-pcmi lib
p   libzita-alsa-pcmi0                          - C++ wrapper around the ALSA API 
```

Then they will be left a little confused as to what to install when `autogen.sh` just complains that they are missing ALSA. This is because the actual package that's needed is called ***libasound2-dev***, which has neither "alsa" nor "lib" in its name, although it is in fact built from the alsa-lib source package. 

After I got the missing ALSA error, I installed only the package `libasound2-dev` and it was resolved, and pnmixer is working fine so I am sure that it is the correct dependency. Perhaps in other non-Debian distros the package is actually called alsa-lib.

It just took me a while to figure all this out so I thought it would be worth mentioning this in the README in case anyone else (Ubuntu, Mint, etc.) has this issue. All of the other deps are fairly straightforward.

**Comment by elboulangero** [comment]
Thanks for the feedback, indeed, if you don't know that alsa libraries are named libasound on Debian, you're in trouble for some time. I had a quick look on the net, and the package is named alsa-lib on Gentoo and Archlinux, for example. Anyway, updated readme in 92bc682ced8b49a722879948de314964cf82bb20. Thanks !
