### ISSUE TITLE
Vertical slider instead horizontal

### ISSUE THREAD

**Issue by frankicia** [nicklan/pnmixer#80]
Trying to get the slider in a horizontal way, but there is no option, I saw that it is possible to get it (for example in Manjaro)

My system is working with Openbox, I compiled the latest version from here.

Thanks

**Comment by hasufell** [comment]
I think the gtk2 version still has a horizontal slider, you could try that one.

**Comment by frankicia** [comment]
Yes, you right! Thanks

May be add the option? I don't know how much effort could be
