### ISSUE TITLE
when volume is 0 pnmixer still displays "some" volume in systray icon

### ISSUE THREAD

**Issue by landroni** [nicklan/pnmixer#85]
Possibly related to #32. 

Pnmixer will display same icon whether volume is at 31% or at 0%. This is a bit confusing. I suspect that when volume is at 0%, a completely empty icon should be used. 

My gripe comes from the fact that whenever I connect my USB DAC for some reason the base level is always 0, so I always get confused why there is no sound when mixer icon shows *some* volume...

**Comment by landroni** [comment]
In all likelihood the icons concerned, using Faenza-Darker theme, are (whichever size): 
/usr/share/icons/Faenza-Dark/status/64/audio-volume-low-zero-panel.png
/usr/share/icons/Faenza-Dark/status/64/audio-volume-low.png


What I always see, whether 0% or 31% volume is: 
![audio-volume-low](https://cloud.githubusercontent.com/assets/1318567/9027835/8f2a7d8a-3964-11e5-813d-71251f999b20.png)

IMO for 0% we should see: 
![audio-volume-low-zero-panel](https://cloud.githubusercontent.com/assets/1318567/9027840/a38585ae-3964-11e5-8324-c8a07a2b8e9c.png)

**Comment by elboulangero** [comment]
Well I'm not certain about the "audio-volume-low-zero-panel", but there's a "audio-volume-off" that does just as well. I think it's the one we're supposed to use.

**Comment by elboulangero** [comment]
Have a look at the branch `volume-icon-when-zero` I believe it does the trick :)

**Comment by landroni** [comment]
Yup, this does it nicely. (Sorry for the unintended closing/opening.)

**Comment by elboulangero** [comment]
@hasufell I let you review and merge, it's trivial..

@hasufell BTW, we never really discussed that, but do you prefer that someone else review and merge the work of the another ? Or do you find it OK if the same person does the commit and merge the branch without review ?

**Comment by hasufell** [comment]
@elboulangero since not many people are currently active here, just create a PR and wait a few days if someone says :-1: ...otherwise, just merge. If it's a trivial patch, then I believe nicklan already said those are fine to just push.

**Comment by elboulangero** [comment]
Merged
