### ISSUE TITLE
Install PNMixer icons in a better directory

### ISSUE THREAD

**Issue by elboulangero** [nicklan/pnmixer#86]
At the moment, PNMixer icons are installed in `pnmixer/pixmaps`. It's OK as long as it's used only by PNMixer, but the system doesn't find it.

Therefore:
- there's no PNMixer icons in the application menu (furthermore, the icon name in the desktop file is wrong)
- we can't use the PNMixer icons in notifications

I guess we should simply install icons in `/usr/share/icons`, but I'm not an expert on this topic, maybe someone knows better.

**Comment by hasufell** [comment]
`/usr/share/icons/hicolor/128x128/apps/` is the correct location to install them

**Comment by hasufell** [comment]
789a3ee7e1bff47e177da4592129282685041c73 in icons branch

**Comment by elboulangero** [comment]
:+1:

**Comment by elboulangero** [comment]
Merged
