### ISSUE TITLE
add separator between Vol Ctrl and Prefs

### ISSUE THREAD

**Issue by landroni** [nicklan/pnmixer#93]
Yet another cosmetic enhancement. Please consider adding a separator between `Volume Control` and `Prefs`. There is already a separator between `About` and `Quit`, and I suspect it makes sense UI-wise to have one before `Prefs`.

**Comment by hasufell** [comment]
I like the way it is currently.

**Comment by landroni** [comment]
For me there seems to be a logical separation between `Mute/Vol Ctrl` items and `Prefs/Alsa/About`. But this is no doubt a matter of taste, so closing issue...
