### ISSUE TITLE
When PNMixer card changes, the volume showed is wrong

### ISSUE THREAD

**Issue by elboulangero** [nicklan/pnmixer#94]
@landroni said:

> Hmm... With Master volume at 55%, what I get is:
> 
>     systray icon at full tilt (probably 100%)
>     systray tooltip at 100%
>     if I click on systray icon, I see volume at 55%
> 
> Moving it there to 57% adjusts both icon and tooltip to correct values...

**Comment by hasufell** [comment]
I only have one card, so I cannot really test this. But my suspicion is that we need to replace this
```
void apply_prefs(gint alsa_change) {
[...]
  if (alsa_change)
    alsa_init();
[...]
}
```
With this:
```
void apply_prefs(gint alsa_change) {
[...]
  if (alsa_change)
    do_alsa_reinit();
[...]
}
```

**Comment by elboulangero** [comment]
Cool ! I didn't know about this `do_alsa_reinit()` thing... OK I'll test that right now

**Comment by elboulangero** [comment]
Pushed on branch https://github.com/nicklan/pnmixer/tree/fix-volume-on-card-change

Actually the code in `apply_prefs()` was OK, because basically the job that `do_alsa_reinit()` does was explicitly done afterward (ie, update icon and tooltip).

But the bugs came from the automatic card change when the current card is unplugged, in `alsa.c`.

**Comment by elboulangero** [comment]
@landroni Hey, you can also give a try to this branch, I tested it's OK, but two tests are always better than one

**Comment by landroni** [comment]
Yup, this does it for me too.

**Comment by hasufell** [comment]
so can we merge this and then move on with the translation? I think we should be good to go then for the release

**Comment by landroni** [comment]
@hasufell Is #87 hard to implement? Any chance it'll squeeze into the release?

**Comment by elboulangero** [comment]
I didn't look at it yet. I bet it's not a big thing, I'll give it a try asap

**Comment by elboulangero** [comment]
Merged
