### ISSUE TITLE
Option to use the default system icon theme

### ISSUE THREAD

**Issue by AladW** [nicklan/pnmixer#95]
Would it be reasonable to implement a "Default" option for the icon theme? For example, if the user icon settings (via GTK settings) are set to Faenza-Dark, so would the PNMixer icon.

**Comment by elboulangero** [comment]
Yep, I agree, it's something we should implement in the 0.7 version.

**Comment by hasufell** [comment]
How about we remove the featuritis of choosing a specific icon theme and _just_ use the system one? I don't see why having different icon themes here is something useful to support.

**Comment by elboulangero** [comment]
So we can only choose between PNMixer icon and current theme icon ? Sounds OK to me. I agree with you, choosing between available icon themes seems useless (and very unusual). I don't know why this feature existed in the first place.

**Comment by AladW** [comment]
Nice, greatly appreciated. :+1:
