### ISSUE TITLE
minimum gtk3 requirement

### ISSUE THREAD

**Issue by landroni** [nicklan/pnmixer#97]
I managed to build pnmixer against gtk3 v3.4 (configure didn't complain), but it fails at run-time: 

    liv@liv-HP-Compaq-dc7900:~$ pnmixer 

    ** (pnmixer:15747): WARNING **: /usr/share/pnmixer/ui/popup_window-gtk3.glade: required gtk+ version 3.6, current version is 3.4
    /usr/share/pnmixer/ui/popup_window-gtk3.glade: required gtk+ version 3.6, current version is 3.4

Is there a minimum version requirement? And should configure catch this and complain?

**Comment by hasufell** [comment]
> Is there a minimum version requirement?

yes, see the readme (3.6 minimum)

it just seems configure.ac is not up2date https://github.com/nicklan/pnmixer/blob/master/configure.ac#L56

**Comment by hasufell** [comment]
travis fixed in 4e8b1806e715a19f25e9d54897d909e14bc1e3de
