### ISSUE TITLE
notify.c:166:6: error: conflicting types for ‘do_notify_text’

### ISSUE THREAD

**Issue by eka-putra** [nicklan/pnmixer#98]
hi , i try to install pnmixer in Xubuntu 14.04, but an error like this:

Making all in data
make[1]: Entering directory `/home/x43u/github/pnmixer/data'
Making all in desktop
make[2]: Entering directory `/home/x43u/github/pnmixer/data/desktop'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/x43u/github/pnmixer/data/desktop'
Making all in icons
make[2]: Entering directory `/home/x43u/github/pnmixer/data/icons'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/x43u/github/pnmixer/data/icons'
Making all in pixmaps
make[2]: Entering directory `/home/x43u/github/pnmixer/data/pixmaps'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/x43u/github/pnmixer/data/pixmaps'
Making all in ui
make[2]: Entering directory `/home/x43u/github/pnmixer/data/ui'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/x43u/github/pnmixer/data/ui'
make[2]: Entering directory `/home/x43u/github/pnmixer/data'
make[2]: Nothing to be done for `all-am'.
make[2]: Leaving directory `/home/x43u/github/pnmixer/data'
make[1]: Leaving directory `/home/x43u/github/pnmixer/data'
Making all in po
make[1]: Entering directory `/home/x43u/github/pnmixer/po'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/x43u/github/pnmixer/po'
Making all in src
make[1]: Entering directory `/home/x43u/github/pnmixer/src'
gcc -DPACKAGE_NAME=\"pnmixer\" -DPACKAGE_TARNAME=\"pnmixer\" -DPACKAGE_VERSION=\"0.6-rc2\" -DPACKAGE_STRING=\"pnmixer\ 0.6-rc2\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"pnmixer\" -DVERSION=\"0.6-rc2\" -DSTDC_HEADERS=1 -DWITH_GTK3=/\*\*/ -DHAVE_LIBX11=1 -DHAVE_LIBM=1 -DNDEBUG=/\*\*/ -DGETTEXT_PACKAGE=\"pnmixer\" -I.  -DPACKAGE_DATA_DIR=\""/usr/local/share"\" -DPACKAGE_LOCALE_DIR=\""/usr/local/share/locale"\" -pthread -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/alsa     -g -O2 -O2 -MT notify.o -MD -MP -MF .deps/notify.Tpo -c -o notify.o notify.c

notify.c:166:6: error: conflicting types for ‘do_notify_text’
 void do_notify_text(gchar *text) {}
      ^
In file included from notify.c:24:0:
notify.h:32:6: note: previous declaration of ‘do_notify_text’ was here
 void do_notify_text(const gchar *body, const gchar *text);
      ^
make[1]: *** [notify.o] Error 1
make[1]: Leaving directory `/home/x43u/github/pnmixer/src'
make: *** [all-recursive] Error 1

how do I fix this?

**Comment by hasufell** [comment]
Please use the real `0.6` release: https://github.com/nicklan/pnmixer/releases
