### ISSUE TITLE
replace mute/unmute menu item with a checkbox

### ISSUE THREAD

**Issue by landroni** [nicklan/pnmixer#99]
As far as I go the `Mute/Unmute` menu item is slightly confusing UI-wise. I think it would be more intuitive to have a `Mute` checkbox instead. This is what e.g. does xfce4-mixer panel plugin.

**Comment by elboulangero** [comment]
Sounds wise

**Comment by hasufell** [comment]
`on_mute_clicked` and `get_mute_state` have some serious state-foo that causes signal bugs and other crap if you want multiple checkboxes/widgets to connect to `on_mute_clicked`. It simply needs a rewrite.

**Comment by hasufell** [comment]
done with gtk3 part
